name: Build and Deploy Node.js REST API to Azure

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Check out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'  # Make sure this matches your Node.js version

    - name: Azure Login
      uses: Azure/login@v2.2.0
  

    - run: npm install  # Install dependencies

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wom-projekt'  # Replace with your Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Make sure this secret is set in GitHub
